name: Create YC infrastructure

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_yc_prep:
        description: Enter "YES" to run YC-prep project
        required: false
        default: 'no'
      run_yc_infra:
        description: Enter "YES" to run YC-infra project
        required: false
        default: 'no'

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/terraform-plugin-cache
  TF_VAR_cloud_id: ${{ vars.YC_CLOUD_ID }}
  TF_VAR_folder_id: ${{ vars.YC_FOLDER_ID }}
  TF_VAR_sa_key_file: ${{ vars.YC_INFRA_SA_KEY_FILE }}  # переменная с аттрибутами файла, не файл с ключами
  TF_VAR_aws_access_file: ${{ vars.YC_INFRA_AWS_ACCESS_FILE }}  # переменная с аттрибутами файла, не файл с ключами
  TF_VAR_bucket: ${{ vars.YC_INFRA_BUCKET }}
  TF_VAR_backend_file: ${{ vars.YC_INFRA_BACKEND_FILE }}
  TF_VAR_vars_file: ${{ vars.YC_INFRA_VARS_FILE }}
  TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      yc-prep: ${{ steps.filter.outputs.yc-prep }}
      yc-infra: ${{ steps.filter.outputs.yc-infra }}
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            yc-prep:
              - 'yc_prep/**'
            yc-infra:
              - 'yc_infra/**'

  # проект подготовки YC для деплоя инфраструктуры
  prepare-plan:
    name: YC-prep project plan
    needs: detect-changes
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_yc_prep == 'YES') ||
      (github.event_name == 'pull_request' && needs.detect-changes.outputs.yc-prep == 'true')
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_prep

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_adm_sa_key: ${{ secrets.YC_ADM_SA_KEY }}
      YC_PREP_BACKEND_DB: ${{ fromJSON(secrets.YC_PREP_BACKEND).db }}
      YC_PREP_BACKEND_TABLE: ${{ fromJSON(secrets.YC_PREP_BACKEND).table }}
      YC_PREP_BACKEND_BUCKET: ${{ fromJSON(secrets.YC_PREP_BACKEND).bucket }}
      YC_PREP_BACKEND_KEY: ${{ fromJSON(secrets.YC_PREP_BACKEND).key }}

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6
      
      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Terraform init
        run: |
          terraform init \
          -backend-config="endpoint=$TF_BACKEND_S3" \
          -backend-config="dynamodb_endpoint=$YC_PREP_BACKEND_DB" \
          -backend-config="dynamodb_table=$YC_PREP_BACKEND_TABLE" \
          -backend-config="bucket=$YC_PREP_BACKEND_BUCKET" \
          -backend-config="key=$YC_PREP_BACKEND_KEY" \
          -input=false

      - name: Terraform format check
        run: terraform fmt -check
      
      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: prep_plan
        run: |
          terraform plan -no-color -input=false -out=prep_tfplan
          terraform show -no-color prep_tfplan > prep_plan.txt

      - name: Upload prepare plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-prep-plan
          path: yc_prep/prep_tfplan
          retention-days: 1
      
      - name: Comment PR with prepare plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const prep_plan = fs.readFileSync('./yc_prep/prep_plan.txt', 'utf8');
            const body = `## Terraform Plan

            <details>
            <summary>Show Plan</summary>

            \`\`\`hcl
            ${prep_plan.substring(0, 60000)}
            \`\`\`

            </details>`;

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
  
  prepare-apply:
    name: YC-prep project apply
    needs: prepare-plan
    if: needs.prepare-plan.result == 'success'
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_prep

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_adm_sa_key: ${{ secrets.YC_ADM_SA_KEY }}
      YC_PREP_BACKEND_DB: ${{ fromJSON(secrets.YC_PREP_BACKEND).db }}
      YC_PREP_BACKEND_TABLE: ${{ fromJSON(secrets.YC_PREP_BACKEND).table }}
      YC_PREP_BACKEND_BUCKET: ${{ fromJSON(secrets.YC_PREP_BACKEND).bucket }}
      YC_PREP_BACKEND_KEY: ${{ fromJSON(secrets.YC_PREP_BACKEND).key }}

    environment: review_tfplan

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Terraform init
        run: |
          terraform init \
          -backend-config="endpoint=$TF_BACKEND_S3" \
          -backend-config="dynamodb_endpoint=$YC_PREP_BACKEND_DB" \
          -backend-config="dynamodb_table=$YC_PREP_BACKEND_TABLE" \
          -backend-config="bucket=$YC_PREP_BACKEND_BUCKET" \
          -backend-config="key=$YC_PREP_BACKEND_KEY" \
          -input=false

      - name: Download prepare plan
        uses: actions/download-artifact@v8
        with:
          name: terraform-prep-plan
          path: yc_prep

      - name: Terraform apply
        run: terraform apply -auto-approve prep_tfplan

      - name: Delete prepare tfplan 
        if: always()
        uses: geekyeggo/delete-artifact@v6
        with:
          name: terraform-prep-plan

  # проект деплоя инфраструктуры
  infra-plan:
    name: YC-infra project plan
    needs: [ detect-changes, prepare-apply ]
    if: |
      always() && needs.detect-changes.result == 'success' &&
      (needs.prepare-plan.result == 'success' || needs.prepare-plan.result == 'skipped') &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.run_yc_infra == 'YES') ||
        (
          github.event_name == 'pull_request' &&
          (needs.detect-changes.outputs.yc-infra == 'true' || needs.detect-changes.outputs.yc-prep == 'true') &&
          (needs.prepare-apply.result == 'success' || needs.prepare-apply.result == 'skipped')
        )
      )
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_infra
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_vm_user_name: ${{ secrets.VM_USER_NAME }}
      TF_VAR_pub_ssh_key: ${{ secrets.PUB_SSH_KEY }}
      TF_VAR_ssh_key_path: ${{ vars.SSH_KEY_PATH }}
      TF_VAR_ansible_inventory: ${{ vars.ANSIBLE_INVENTORY }}
      TF_VAR_bastion_access: ${{ secrets.BASTION_ACCESS }}
      TF_VAR_app_data: ${{ vars.APP_DATA }}

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6
      
      - name: Check and required files
        run: |
          set -euo pipefail
          check_file () {
            local key="$1"
            aws s3api head-object \
              --bucket "${{ fromJSON(vars.YC_INFRA_BUCKET).name }}" \
              --key "$key" \
              --endpoint-url "$TF_BACKEND_S3" > /dev/null 2>&1 || \
              { echo "File $key not found. Run the Terraform yc-prep project."; exit 1; }
          }
          check_file "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}"
          check_file "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}"
          check_file "${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}"
          check_file "${{ fromJSON(vars.YC_INFRA_VARS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}"
          echo "The required files were found."

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Download infrastructure project configs files
        run: |
          mkdir -p "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}"
          mkdir -p "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform format check
        run: terraform fmt -check
      
      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: infra_plan
        run: |
          terraform plan -no-color -input=false -out=infra_tfplan
          terraform show -no-color infra_tfplan > infra_plan.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-infra-plan
          path: yc_infra/infra_tfplan
          retention-days: 1
      
      - name: Comment PR with infrastructure plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const infra_plan = fs.readFileSync('./yc_infra/infra_plan.txt', 'utf8');
            const body = `## Terraform Plan

            <details>
            <summary>Show Plan</summary>

            \`\`\`hcl
            ${infra_plan.substring(0, 60000)}
            \`\`\`

            </details>`;

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
  
  infra-apply:
    name: YC-infra project apply
    needs: infra-plan
    if: needs.infra-plan.result == 'success'
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_infra

    environment: review_tfplan

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_vm_user_name: ${{ secrets.VM_USER_NAME }}
      TF_VAR_pub_ssh_key: ${{ secrets.PUB_SSH_KEY }}
      TF_VAR_ssh_key_path: ${{ vars.SSH_KEY_PATH }}
      TF_VAR_ansible_inventory: ${{ vars.ANSIBLE_INVENTORY }}
      TF_VAR_bastion_access: ${{ secrets.BASTION_ACCESS }}
      TF_VAR_app_data: ${{ vars.APP_DATA }}

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Download infrastructure project configs files
        run: |
          mkdir -p "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}"
          mkdir -p "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" --endpoint-url="$TF_BACKEND_S3"

      - name: Generate token
        id: set_secret_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.SET_SECRET_APP_ID }}
          private-key: ${{ secrets.SET_SECRET_APP_PRIVATE_KEY }}
          repositories: |
            dip-k8s
            dip-app
      
      - name: Set vars in dip-k8s, dip-app repo
        env:
          GH_TOKEN: ${{ steps.set_secret_token.outputs.token }}
          ANSIBLE_INVENTORY: ${{ vars.ANSIBLE_INVENTORY }}
          TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}
          YC_INFRA_BUCKET: ${{ vars.YC_INFRA_BUCKET }}
          YC_INFRA_SA_KEY_FILE: ${{ vars.YC_INFRA_SA_KEY_FILE }}  # переменная с аттрибутами файла, не файл с ключами
          APP_DATA: ${{ vars.APP_DATA }}
        run: |
          gh variable set ANSIBLE_INVENTORY --repo "rizl-ad/dip-k8s" --body "$ANSIBLE_INVENTORY"
          gh variable set TF_BACKEND_S3 --repo "rizl-ad/dip-k8s" --body "$TF_BACKEND_S3"
          gh variable set TF_BACKEND_S3 --repo "rizl-ad/dip-app" --body "$TF_BACKEND_S3"
          gh variable set YC_INFRA_BUCKET --repo "rizl-ad/dip-k8s" --body "$YC_INFRA_BUCKET"
          gh variable set YC_INFRA_BUCKET --repo "rizl-ad/dip-app" --body "$YC_INFRA_BUCKET"
          gh variable set YC_INFRA_SA_KEY_FILE --repo "rizl-ad/dip-k8s" --body "$YC_INFRA_SA_KEY_FILE"
          gh variable set APP_DATA --repo "rizl-ad/dip-app" --body "$APP_DATA"

      - name: Set secret in dip-app repo
        env:
          GH_TOKEN: ${{ steps.set_secret_token.outputs.token }}
          SA_KEY_FILE_PATH: "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}"
        run: |
          gh secret set YC_INFRA_SA_KEY --repo "rizl-ad/dip-app" < "$SA_KEY_FILE_PATH"

      - name: Terraform init
        run: terraform init -input=false

      - name: Download infrastructure plan
        uses: actions/download-artifact@v8
        with:
          name: terraform-infra-plan
          path: yc_infra

      - name: Terraform apply
        run: terraform apply -auto-approve infra_tfplan

      - name: Delete infrastructure tfplan
        if: always()
        uses: geekyeggo/delete-artifact@v6
        with:
          name: terraform-infra-plan

  k8s:
    name: Deploy Kubernetes
    needs: infra-apply
    if: needs.infra-apply.result == 'success'
    runs-on: ubuntu-24.04

    steps:
      - name: Generate token
        id: wf_call_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.REMOTE_WORKFLOW_CALL_APP_ID }}
          private-key: ${{ secrets.REMOTE_WORKFLOW_CALL_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: dip-k8s

      - name: Remote workflow call
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.wf_call_token.outputs.token }}
          repository: rizl-ad/dip-k8s
          event-type: deploy-k8s
