name: Create YC infrastructure

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_yc_prep:
        description: Run YC-prep project
        required: false
        default: 'false'
      run_yc_infra:
        description: Run YC-infra project
        required: false
        default: 'false'

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/terraform-plugin-cache
  # TF_VAR_cloud_id: ${{ vars.YC_CLOUD_ID }}
  # TF_VAR_folder_id: ${{ vars.YC_FOLDER_ID }}
  # TF_VAR_sa_key_file: ${{ vars.YC_INFRA_SA_KEY_FILE }}  # переменная с аттрибутами файла, не файл с ключами
  # TF_VAR_aws_access_file: ${{ vars.YC_INFRA_AWS_ACCESS_FILE }}  # переменная с аттрибутами файла, не файл с ключами
  # TF_VAR_bucket: ${{ vars.YC_INFRA_BUCKET }}
  # TF_VAR_backend_file: ${{ vars.YC_INFRA_BACKEND_FILE }}
  # TF_VAR_vars_file: ${{ vars.YC_INFRA_VARS_FILE }}
  # TF_BACKEND_S3: ${{ vars.TF_BACKEND_S3 }}

permissions:
  contents: read
  pull-requests: write

jobs:

  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      yc-prep: ${{ steps.filter.outputs.yc-prep }}
      yc-infra: ${{ steps.filter.outputs.yc-infra }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            yc-prep:
              - 'yc_prep/**'
            yc-infra:
              - 'yc_infra/**'

  # проект подготовки YC для деплоя инфраструктуры
  prepare-plan:
    name: YC-prep project plan
    needs: detect-changes
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_yc_prep == 'true') ||
      (github.event_name == 'pull_request' && needs.detect-changes.outputs.yc-prep == 'true')
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_prep
    
    outputs:
      yc_prep_backend_db: ${{ steps.repo_vars.outputs.YC_PREP_BACKEND_DB }}
      yc_prep_backend_table: ${{ steps.repo_vars.outputs.YC_PREP_BACKEND_TABLE }}
      yc_prep_backend_bucket: ${{ steps.repo_vars.outputs.YC_PREP_BACKEND_BUCKET }}
      yc_prep_backend_key: ${{ steps.repo_vars.outputs.YC_PREP_BACKEND_KEY }}
      tf_var_cloud_id: ${{ steps.repo_vars.outputs.TF_VAR_cloud_id }}
      tf_var_folder_id: ${{ steps.repo_vars.outputs.TF_VAR_folder_id }}
      tf_backend_s3: ${{ steps.repo_vars.outputs.TF_BACKEND_S3 }}
      tf_var_sa_key_file: ${{ steps.repo_vars.outputs.TF_VAR_sa_key_file }}
      tf_var_aws_access_file: ${{ steps.repo_vars.outputs.TF_VAR_aws_access_file }}
      tf_var_bucket: ${{ steps.repo_vars.outputs.TF_VAR_bucket }}
      tf_var_backend_file: ${{ steps.repo_vars.outputs.TF_VAR_backend_file }}
      tf_var_vars_file: ${{ steps.repo_vars.outputs.TF_VAR_vars_file }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_adm_sa_key: ${{ secrets.YC_ADM_SA_KEY }}
      # YC_PREP_BACKEND_DB: ${{ fromJSON(vars.YC_PREP_BACKEND).db }}
      # YC_PREP_BACKEND_TABLE: ${{ fromJSON(vars.YC_PREP_BACKEND).table }}
      # YC_PREP_BACKEND_BUCKET: ${{ fromJSON(vars.YC_PREP_BACKEND).bucket }}
      # YC_PREP_BACKEND_KEY: ${{ fromJSON(vars.YC_PREP_BACKEND).key }}

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6
      
      # Маскировка переменных, чтобы они не отображались в логе workflow
      # Значения не заданы как секреты чтобы значения отображались в web-интерфейсе
      - name: Mask repository variables
        id: repo_vars
        # TF_VAR_sa_key_file - переменная с аттрибутами файла, не файл с ключами
        # TF_VAR_aws_access_file - переменная с аттрибутами файла, не файл с ключами
        run: |
          M_YC_PREP_BACKEND_DB=${{ fromJSON(vars.YC_PREP_BACKEND).db }}
          M_YC_PREP_BACKEND_TABLE=${{ fromJSON(vars.YC_PREP_BACKEND).table }}
          M_YC_PREP_BACKEND_BUCKET=${{ fromJSON(vars.YC_PREP_BACKEND).bucket }}
          M_YC_PREP_BACKEND_KEY=${{ fromJSON(vars.YC_PREP_BACKEND).key }}
          M_TF_VAR_cloud_id=${{ vars.YC_CLOUD_ID }}
          M_TF_VAR_folder_id=${{ vars.YC_FOLDER_ID }}
          M_TF_BACKEND_S3=${{ vars.TF_BACKEND_S3 }}
          M_TF_VAR_sa_key_file=${{ vars.YC_INFRA_SA_KEY_FILE }}
          M_TF_VAR_aws_access_file=${{ vars.YC_INFRA_AWS_ACCESS_FILE }}
          M_TF_VAR_bucket=${{ vars.YC_INFRA_BUCKET }}
          M_TF_VAR_backend_file=${{ vars.YC_INFRA_BACKEND_FILE }}
          M_TF_VAR_vars_file=${{ vars.YC_INFRA_VARS_FILE }}

          echo "::add-mask::$M_YC_PREP_BACKEND_DB"
          echo "::add-mask::$M_YC_PREP_BACKEND_TABLE"
          echo "::add-mask::$M_YC_PREP_BACKEND_BUCKET"
          echo "::add-mask::$M_YC_PREP_BACKEND_KEY"
          echo "::add-mask::$M_TF_VAR_cloud_id"
          echo "::add-mask::$M_TF_VAR_folder_id"
          echo "::add-mask::$M_TF_BACKEND_S3"
          echo "::add-mask::$M_TF_VAR_sa_key_file"
          echo "::add-mask::$M_TF_VAR_aws_access_file"
          echo "::add-mask::$M_TF_VAR_bucket"
          echo "::add-mask::$M_TF_VAR_backend_file"
          echo "::add-mask::$M_TF_VAR_vars_file"

          echo "YC_PREP_BACKEND_DB=$M_YC_PREP_BACKEND_DB" >> $GITHUB_ENV
          echo "YC_PREP_BACKEND_TABLE=$M_YC_PREP_BACKEND_TABLE" >> $GITHUB_ENV
          echo "YC_PREP_BACKEND_BUCKET=$M_YC_PREP_BACKEND_BUCKET" >> $GITHUB_ENV
          echo "YC_PREP_BACKEND_KEY=$M_YC_PREP_BACKEND_KEY" >> $GITHUB_ENV
          echo "TF_VAR_cloud_id=$M_TF_VAR_cloud_id" >> $GITHUB_ENV
          echo "TF_VAR_folder_id=$M_TF_VAR_folder_id" >> $GITHUB_ENV
          echo "TF_BACKEND_S3=$M_TF_BACKEND_S3" >> $GITHUB_ENV
          echo "TF_VAR_sa_key_file=$M_TF_VAR_sa_key_file" >> $GITHUB_ENV
          echo "TF_VAR_aws_access_file=$M_TF_VAR_aws_access_file" >> $GITHUB_ENV
          echo "TF_VAR_bucket=$M_TF_VAR_bucket" >> $GITHUB_ENV
          echo "TF_VAR_backend_file=$M_TF_VAR_backend_file" >> $GITHUB_ENV
          echo "TF_VAR_vars_file=$M_TF_VAR_vars_file" >> $GITHUB_ENV

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Terraform init
        run: |
          terraform init \
          -backend-config="endpoint=$TF_BACKEND_S3" \
          -backend-config="dynamodb_endpoint=$YC_PREP_BACKEND_DB" \
          -backend-config="dynamodb_table=$YC_PREP_BACKEND_TABLE" \
          -backend-config="bucket=$YC_PREP_BACKEND_BUCKET" \
          -backend-config="key=$YC_PREP_BACKEND_KEY" \
          -input=false

      - name: Terraform format check
        run: terraform fmt -check
      
      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: prep_plan
        run: |
          terraform plan -no-color -input=false -out=prep_tfplan
          terraform show -no-color prep_tfplan > prep_plan.txt

      - name: Upload prepare plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-prep-plan
          path: yc_prep/prep_tfplan
          retention-days: 1
      
      - name: Comment PR with prepare plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const prep_plan = fs.readFileSync('./yc_prep/prep_plan.txt', 'utf8');
            const body = `## Terraform Plan

            <details>
            <summary>Show Plan</summary>

            \`\`\`hcl
            ${prep_plan.substring(0, 60000)}
            \`\`\`

            </details>`;

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
  
  prepare-apply:
    name: YC-prep project apply
    needs: prepare-plan
    if: needs.prepare-plan.result == 'success'
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_prep

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_adm_sa_key: ${{ secrets.YC_ADM_SA_KEY }}
      TF_VAR_CLOUD_ID: ${{ needs.prepare-plan.outputs.tf_var_cloud_id }}
      TF_VAR_FOLDER_ID: ${{ needs.prepare-plan.outputs.tf_var_folder_id }}
      # YC_PREP_BACKEND_DB: ${{ fromJSON(vars.YC_PREP_BACKEND).db }}
      # YC_PREP_BACKEND_TABLE: ${{ fromJSON(vars.YC_PREP_BACKEND).table }}
      # YC_PREP_BACKEND_BUCKET: ${{ fromJSON(vars.YC_PREP_BACKEND).bucket }}
      # YC_PREP_BACKEND_KEY: ${{ fromJSON(vars.YC_PREP_BACKEND).key }}
      YC_PREP_BACKEND_DB: ${{ needs.prepare-plan.outputs.yc_prep_backend_db }}
      YC_PREP_BACKEND_TABLE: ${{ needs.prepare-plan.outputs.yc_prep_backend_table }}
      YC_PREP_BACKEND_BUCKET: ${{ needs.prepare-plan.outputs.yc_prep_backend_bucket }}
      YC_PREP_BACKEND_KEY: ${{ needs.prepare-plan.outputs.yc_prep_backend_key }}
      TF_BACKEND_S3: ${{ needs.prepare-plan.outputs.tf_backend_s3 }}
      TF_VAR_SA_KEY_FILE: ${{ needs.prepare-plan.outputs.tf_var_sa_key_file }}
      TF_VAR_AWS_ACCESS_FILE: ${{ needs.prepare-plan.outputs.tf_var_aws_access_file }}
      TF_VAR_BUCKET: ${{ needs.prepare-plan.outputs.tf_var_bucket }}
      TF_VAR_BACKEND_FILE: ${{ needs.prepare-plan.outputs.tf_var_backend_file }}
      TF_VAR_VARS_FILE: ${{ needs.prepare-plan.outputs.tf_var_vars_file }}

    environment: review_tfplan

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Terraform init
        run: |
          terraform init \
          -backend-config="endpoint=$TF_BACKEND_S3" \
          -backend-config="dynamodb_endpoint=$YC_PREP_BACKEND_DB" \
          -backend-config="dynamodb_table=$YC_PREP_BACKEND_TABLE" \
          -backend-config="bucket=$YC_PREP_BACKEND_BUCKET" \
          -backend-config="key=$YC_PREP_BACKEND_KEY" \
          -input=false

      - name: Download prepare plan
        uses: actions/download-artifact@v8
        with:
          name: terraform-prep-plan
          path: yc_prep

      - name: Terraform apply
        run: terraform apply -auto-approve prep_tfplan

      - name: Delete prepare tfplan 
        if: always()
        uses: geekyeggo/delete-artifact@v6
        with:
          name: terraform-prep-plan

  # проект деплоя инфраструктуры
  infra-plan:
    name: YC-infra project plan
    needs: [ detect-changes, prepare-apply ]
    if: |
      always() && needs.detect-changes.result == 'success' &&
      (needs.prepare-plan.result == 'success' || needs.prepare-plan.result == 'skipped') &&
      (
        (github.event_name == 'workflow_dispatch' && github.event.inputs.run_yc_infra == 'true') ||
        (
          github.event_name == 'pull_request' &&
          (needs.detect-changes.outputs.yc-infra == 'true' || needs.detect-changes.outputs.yc-prep == 'true') &&
          (needs.prepare-apply.result == 'success' || needs.prepare-apply.result == 'skipped')
        )
      )
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_infra

    outputs:
      tf_var_ssh_key_path: ${{ steps.repo_infra_vars.outputs.TF_VAR_ssh_key_path }}
      tf_var_ansible_inventory: ${{ steps.repo_infra_vars.outputs.TF_VAR_ansible_inventory }}
      tf_var_bastion_access: ${{ steps.repo_infra_vars.outputs.TF_VAR_bastion_access }}
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_vm_user_name: ${{ secrets.VM_USER_NAME }}
      TF_VAR_pub_ssh_key: ${{ secrets.PUB_SSH_KEY }}
      TF_VAR_CLOUD_ID: ${{ needs.prepare-plan.outputs.tf_var_cloud_id }}
      TF_VAR_FOLDER_ID: ${{ needs.prepare-plan.outputs.tf_var_folder_id }}
      TF_BACKEND_S3: ${{ needs.prepare-plan.outputs.tf_backend_s3 }}
      TF_VAR_SA_KEY_FILE: ${{ needs.prepare-plan.outputs.tf_var_sa_key_file }}
      TF_VAR_AWS_ACCESS_FILE: ${{ needs.prepare-plan.outputs.tf_var_aws_access_file }}
      TF_VAR_BUCKET: ${{ needs.prepare-plan.outputs.tf_var_bucket }}
      TF_VAR_BACKEND_FILE: ${{ needs.prepare-plan.outputs.tf_var_backend_file }}
      TF_VAR_VARS_FILE: ${{ needs.prepare-plan.outputs.tf_var_vars_file }}
      # TF_VAR_ssh_key_path: ${{ vars.SSH_KEY_PATH }}
      # TF_VAR_ansible_inventory: ${{ vars.ANSIBLE_INVENTORY }}
      # TF_VAR_bastion_access: ${{ vars.BASTION_ACCESS }}

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6
      
            # Маскировка переменных, чтобы они не отображались в логе workflow
      # Значения не заданы как секреты чтобы значения отображались в web-интерфейсе
      - name: Mask repository variables
        id: repo_infra_vars
        # TF_VAR_sa_key_file - переменная с аттрибутами файла, не файл с ключами
        # TF_VAR_aws_access_file - переменная с аттрибутами файла, не файл с ключами
        run: |
          M_TF_VAR_ssh_key_path=${{ vars.SSH_KEY_PATH }}
          M_TF_VAR_ansible_inventory=${{ vars.ANSIBLE_INVENTORY }}
          M_TF_VAR_bastion_access=${{ vars.BASTION_ACCESS }}

          echo "::add-mask::$M_TF_VAR_ssh_key_path"
          echo "::add-mask::$M_TF_VAR_ansible_inventory"
          echo "::add-mask::$M_TF_VAR_bastion_access"

          echo "TF_VAR_ssh_key_path=$M_TF_VAR_ssh_key_path" >> $GITHUB_ENV
          echo "TF_VAR_ansible_inventory=$M_TF_VAR_ansible_inventory" >> $GITHUB_ENV
          echo "TF_VAR_bastion_access=$M_TF_VAR_bastion_access" >> $GITHUB_ENV
      
      - name: Check required files
        run: |
          set -euo pipefail

          check_file () {
            local key="$1"
            aws s3api head-object \
              --bucket "${{ fromJSON(vars.YC_INFRA_BUCKET).name }}" \
              --key "$key" \
              --endpoint-url "${{ vars.TF_BACKEND_S3 }}" > /dev/null 2>&1 || \
              { echo "File $key not found. Run the Terraform yc-prep project."; exit 1; }
          }

          check_file "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}"
          check_file "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}"
          check_file "${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}"
          check_file "${{ fromJSON(vars.YC_INFRA_VARS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}"
          echo "The required files were found."

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Download infrastructure project configs files
        run: |
          mkdir -p "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}"
          mkdir -p "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" "${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform format check
        run: terraform fmt -check
      
      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: infra_plan
        run: |
          terraform plan -no-color -input=false -out=infra_tfplan
          terraform show -no-color infra_tfplan > infra_plan.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-infra-plan
          path: yc_infra/infra_tfplan
          retention-days: 1
      
      - name: Comment PR with infrastructure plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const infra_plan = fs.readFileSync('./yc_infra/infra_plan.txt', 'utf8');
            const body = `## Terraform Plan

            <details>
            <summary>Show Plan</summary>

            \`\`\`hcl
            ${infra_plan.substring(0, 60000)}
            \`\`\`

            </details>`;

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
  
  infra-apply:
    name: YC-infra project apply
    needs: infra-plan
    if: needs.infra-plan.result == 'success'
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./yc_infra

    environment: review_tfplan

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_vm_user_name: ${{ secrets.VM_USER_NAME }}
      TF_VAR_pub_ssh_key: ${{ secrets.PUB_SSH_KEY }}
      TF_VAR_CLOUD_ID: ${{ needs.prepare-plan.outputs.tf_var_cloud_id }}
      TF_VAR_FOLDER_ID: ${{ needs.prepare-plan.outputs.tf_var_folder_id }}
      TF_BACKEND_S3: ${{ needs.prepare-plan.outputs.tf_backend_s3 }}
      TF_VAR_SA_KEY_FILE: ${{ needs.prepare-plan.outputs.tf_var_sa_key_file }}
      TF_VAR_AWS_ACCESS_FILE: ${{ needs.prepare-plan.outputs.tf_var_aws_access_file }}
      TF_VAR_BUCKET: ${{ needs.prepare-plan.outputs.tf_var_bucket }}
      TF_VAR_BACKEND_FILE: ${{ needs.prepare-plan.outputs.tf_var_backend_file }}
      TF_VAR_VARS_FILE: ${{ needs.prepare-plan.outputs.tf_var_vars_file }}
      # TF_VAR_ssh_key_path: ${{ vars.SSH_KEY_PATH }}
      # TF_VAR_ansible_inventory: ${{ vars.ANSIBLE_INVENTORY }}
      # TF_VAR_bastion_access: ${{ vars.BASTION_ACCESS }}
      TF_VAR_ssh_key_path: ${{ needs.infra-plan.outputs.tf_var_ssh_key_path }}
      TF_VAR_ansible_inventory: ${{ needs.infra-plan.outputs.tf_var_ansible_inventory }}
      TF_VAR_bastion_access: ${{ needs.infra-plan.outputs.tf_var_bastion_access }}

    steps:
      - name: Clone repository on runner
        uses: actions/checkout@v6

      - name: Create plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform
        uses: actions/cache@v5
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.13.0"

      - name: Download infrastructure project configs files
        run: |
          mkdir -p "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}"
          mkdir -p "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_SA_KEY_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_AWS_ACCESS_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_BACKEND_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"
          aws s3 cp "s3://${{ fromJSON(vars.YC_INFRA_BUCKET).name }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).dir_path }}/${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" \
            "${{ fromJSON(vars.YC_INFRA_VARS_FILE).name }}" --endpoint-url="${{ vars.TF_BACKEND_S3 }}"

      - name: Terraform init
        run: terraform init -input=false

      - name: Download infrastructure plan
        uses: actions/download-artifact@v8
        with:
          name: terraform-infra-plan
          path: yc_infra

      - name: Terraform apply
        run: terraform apply -auto-approve infra_tfplan

      - name: Delete infrastructure tfplan
        if: always()
        uses: geekyeggo/delete-artifact@v6
        with:
          name: terraform-infra-plan

  k8s-cluster:
    name: Deploy Kubernetes
    needs: infra-apply
    if: needs.infra-apply.result == 'success'
    runs-on: ubuntu-24.04

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.REMOTE_WORKFLOW_CALL_APP_ID }}
          private-key: ${{ secrets.REMOTE_WORKFLOW_CALL_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            dip-yc
            dip-k8s

      - name: Remote workflow call
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: rizl-ad/dip-k8s
          event-type: deploy-k8s
